const translations = {
    "abais": ["but"],
    "aktion": ["action"],
    "albiner": ["white"],
    "apolies": ["sorry"],
    "ba": [" (question marker)"],
    "baksu": ["box", "boxes"],
    "bévakoof": ["stupid", "insane", "crazy"],
    "béyâhend": ["okay", "affirmative"],
    "blemiken": ["speak"],
    "bligau": ["blue"],
    "boissonus": ["drink"],
    "boissonen": ["drink (verb)"],
    "bom": ["good"],
    "bomer": ["love"],
    "bonat": ["gift"],
    "buhdich": ["dumb", "crazy", "stupid"],
    "centrum": ["I/me"],
    "cerebrent": ["know"],
    "cerebrum": ["brain"],
    "cha": ["coffee"],
    "chay": ["something", "thing"],
    "chistando": ["joke"],
    "chukas": ["cat", "cats"],
    "dawr": ["role", "function"],
    "daz": ["that"],
    "degistermen": ["change"],
    "direken": ["tell", "say"],
    "diktonary": ["dictionary"],
    "diz": ["this"],
    "donem": ["give"],
    "dormiren": ["sleep"],
    "durbius": ["animal", "animals"],
    "dzai": ["is in", "is on"],
    "dzwo": ["left"],
    "e": ["and"],
    "ego": ["I/me"],
    "en": ["in"],
    "equival": ["equal"],
    "ergo": ["so", "therefore"],
    "exlirent": ["explain"],
    "fache": ["do"],
    "fazen": ["make"],
    "feminas": ["woman", "women"],
    "folaaz": ["metal"],
    "folaazpersone": ["robot", "bot"],
    "fransosik": ["france", "french"],
    "genus": ["gender"],
    "ghurfa": ["room"],
    "go": ["I/me"],
    "granda": ["very"],
    "gratien": ["thanks"],
    "haiben": ["have"],
    "halo": ["hello"],
    "hamborgar": ["hamburger", "burger"],
    "hic": ["here"],
    "hicsolum": ["today"],
    "homo": ["same"],
    "homoparole": ["homonym"],
    "homosignum": ["synonym"],
    "imaj": ["image"],
    "ind": ["have"],
    "inglisik": ["English", "england"],
    "intelgenri": ["smart"],
    "intapole": ["secret", "information"],
    "ist": ["is", "are"],
    "italiski": ["Italy", "Italian"],
    "jeulo": ["yellow"],
    "kayen": ["can"],
    "ke": ["what"],
    "keken": ["laugh"],
    "ke tal": ["whats up"],
    "keyöntemus": ["how", "what way"],
    "keyuzwo": ["with", "besides", "next to"],
    "komorenden": ["understand"],
    "kribân": ["soon"],
    "kulora": ["colour", "colors"],
    "laterin": ["toilet"],
    "lii": ["inside"],
    "lingue": ["language"],
    "lun": ["moon"],
    "lunum": ["night"],
    "marok": ["Morocco"],
    "marokan": ["Moroccan"],
    "maskulinas": ["man", "men"],
    "me": ["shows it is directed to me"],
    "monomus": ["only"],
    "mort": ["dead"],
    "morten": ["kill"],
    "mui": ["very"],
    "nain": ["no"],
    "naint": ["not"],
    "nainbom": ["bad"],
    "nainchay": ["nothing"],
    "nainthomo": ["different"],
    "nazion": ["nation"],
    "nôchüch": ["annoying"],
    "noi": ["we/us"],
    "nomus": ["name"],
    "noven": ["new"],
    "numerus": ["number"],
    "omni": ["every", "all"],
    "omniblemiken": ["announce"],
    "omniblemikus": ["announcement"],
    "omnipersoni": ["everyone"],
    "onnoek": ["genderless", "neuter", "of unknown gender"],
    "oranj": ["orange"],
    "ow": ["or"],
    "parole": ["word"],
    "pensen": ["think"],
    "per": ["to"],
    "perr": ["too"],
    "personepumilus": ["poll", "people’s choice"],
    "persone": ["people", "person"],
    "pien": ["because"],
    "pizza": ["pizza"],
    "praesen": ["present"],
    "prochrono": ["put it in front of the verb for future tense"],
    "pumilen": ["choose"],
    "pumilus": ["choice"],
    "quanchrono": ["when"],
    "quus": ["any", "who"],
    "reglus": ["rule"],
    "retrochrono": ["put it in front of the verb for past tense"],
    "reuteret": ["again"],
    "route": ["red"],
    "se": ["show it is directed to them"],
    "sang": ["up"],
    "sangaktiven": ["fun"],
    "sangchay": ["important", "importance"],
    "shangaro": ["angel"],
    "shishten": ["poop"],
    "shworz": ["black"],
    "shworza": ["black coffee"],
    "signum": ["meaning"],
    "sol": ["sun"],
    "solsang": ["sunrise"],
    "solsya": ["sunset"],
    "solum": ["day"],
    "sum": ["am"],
    "susaly": ["auto", "self"],
    "sya": ["down"],
    "syaaktiven": ["bored"],
    "te": ["shows it is directed to you"],
    "tu": ["you"],
    "tuf": ["apple"],
    "urinam": ["urinate", "pee"],
    "usa": ["use"],
    "vescum": ["eat"],
    "viden": ["see"],
    "vïowl": ["purple"],
    "vocarus": ["voice"],
    "vor": ["for"],
    "vorke": ["why"],
    "volerem": ["want", "desire"],
    "vruncha": ["green tea"],
    "vrün": ["green"],
    "wilkvenden": ["welcome"],
    "woru": ["tired"],
    "yönetmekus": ["administrator"],
    "yönetmen": ["administrate"],
    "yöntemus": ["method", "way"],
    "you": ["right"],
    "za": ["tea"],
    "zi": ["yes"]
};

// Function to translate from Interpolater English to English
function translateToEnglish(text) {
    const words = text.split(/[\s,]+/); // Split by spaces and commas
    const translatedWords = words.map(word => {
        const definitions = translations[word];
        return definitions ? definitions[0] : word; // Use the first definition
    });
    return translatedWords.join(' ');
}

// Function to translate from English to Interpolater English
function translateToInterpolator(text) {
    const reversedTranslations = Object.fromEntries(Object.entries(translations).flatMap(([k, v]) => v.map(def => [def, k])));
    const words = text.split(/[\s,]+/); // Split by spaces and commas
    const translatedWords = words.map(word => {
        // Check for exact match or similar word
        const interpolaterWord = reversedTranslations[word];
        return interpolaterWord ? interpolaterWord : (Object.keys(reversedTranslations).find(key => key.includes(word)) || word);
    });
    return translatedWords.join(' ');
}

document.getElementById('translateToEnglishButton').addEventListener('click', () => {
    const inputText = document.getElementById('inputText').value;
    const outputText = translateToEnglish(inputText);
    document.getElementById('outputText').value = outputText;
});

document.getElementById('translateToInterpolatorButton').addEventListener('click', () => {
    const inputTextEnglish = document.getElementById('inputTextEnglish').value;
    const outputTextInterpolator = translateToInterpolator(inputTextEnglish);
    document.getElementById('outputTextInterpolator').value = outputTextInterpolator;
});
